"""inicializando as tabelas

Revision ID: 502f432c5273
Revises: 
Create Date: 2024-08-26 14:32:06.286882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502f432c5273'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apelido', sa.String(length=50), nullable=False),
    sa.Column('apelido_importacao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apelido', sa.String(length=50), nullable=True),
    sa.Column('data_referencia', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apelido')
    )
    op.create_table('item_carrinho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('carrinho_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinho.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdf_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('qtd_emb', sa.String(length=50), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('importacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_data')
    op.drop_table('item_carrinho')
    op.drop_table('importacao')
    op.drop_table('carrinho')
    # ### end Alembic commands ###
